### ISSUE TITLE
[Feature Request] Directory option, page numbering

### ISSUE THREAD

**Issue by Luc-Saccoccio** [darylhjd/mangadesk#3]
Is it possible to add an option to specify the directory where mangas are downloaded ?
Edit : Sorry for all the renames :/ If possible, what about page numbering ? Instead of having these bizarre filenames, is it possible to implement automatic page numbering ?
Last question, don't work on this one if you don't like it : Is it possible to have vim keybindings ?

**Comment by darylhjd** [comment]
The chapters are stored according to their original names, and they are already sorted in order (the start of their names allow sorting `x1...png`, `x2...png`, but yes I think a simpler naming scheme would be better.

**Comment by darylhjd** [comment]
Page Numbering:
- I changed it to give friendly page number in the latest release.

Vim Keybindings:
- I am not too sure about vim keybindings, but a reddit comment indicated that vim keybindings seem to be supported (i cant find the link now). If it doesn't work do let me know, I can see what I can do.

Directory for download:
- This was referenced in another issue.
- Since the directory download request is similar to the other request, I'll be closing this issue and using the other issue https://github.com/darylhjd/mangadesk/issues/5 to keep track of the request.
